# Generated by Django 5.0.7 on 2024-07-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ApiGoods.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords_template', models.TextField(blank=True, null=True)),
                ('meta_description_template', models.TextField(blank=True, null=True)),
                ('element_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_alt_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_filename_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_alt_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_filename_template', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='ApiGoods.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='seo_properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_seo_properties', to='ApiGoods.categoryseo'),
        ),
        migrations.CreateModel(
            name='ListProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ApiGoods.property')),
            ],
            bases=('ApiGoods.property',),
        ),
        migrations.CreateModel(
            name='SingleProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ApiGoods.property')),
                ('property_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50)),
            ],
            bases=('ApiGoods.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ApiGoods.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('desired_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ApiGoods.category')),
                ('configurator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ApiGoods.productconfigurator')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/files/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ApiGoods.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords_template', models.TextField(blank=True, null=True)),
                ('meta_description_template', models.TextField(blank=True, null=True)),
                ('element_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_alt_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_filename_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_alt_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_title_template', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_image_filename_template', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='ApiGoods.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seo_properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_seo_properties', to='ApiGoods.productseo'),
        ),
        migrations.CreateModel(
            name='ProductSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/slider/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='ApiGoods.product')),
            ],
        ),
        migrations.CreateModel(
            name='ListPropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('list_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ApiGoods.listproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='ApiGoods.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiGoods.property')),
            ],
            options={
                'unique_together': {('product', 'property')},
            },
        ),
    ]
